# Generated by Django 5.1.5 on 2025-01-29 15:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('osm_id', models.IntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='issues.issue')),
            ],
        ),
    ]
