# Generated by Django 5.1.5 on 2025-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_ideas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideas',
            old_name='reputation',
            new_name='point',
        ),
    ]
