# Generated by Django 5.1.5 on 2025-05-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_ideas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='createdByUser',
        ),
    ]
