# Generated by Django 5.1.5 on 2026-04-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_userideavote"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="faiss_id",
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AddField(
            model_name="issue",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=10,
            ),
        ),
    ]
