# Generated by Django 5.1.5 on 2025-05-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_ideas_createdbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
