# Generated by Django 5.1.5 on 2025-05-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_ideas_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='faiss_id',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
