# Generated by Django 5.1.5 on 2026-04-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_issue_faiss_id_issue_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="issue_from",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
