# Generated by Django 5.1.5 on 2026-06-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_issue_issue_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techsolution",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
