# Generated by Django 5.1.5 on 2026-06-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_alter_techsolution_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techsolutioncomment",
            name="creationDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
