# Generated by Django 5.1.5 on 2025-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_ideas_createdbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='idea_from',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
